server.port=8181
spring.config.activate.on-profile=prod
spring.servlet.multipart.maxFileSize=4096MB
spring.servlet.multipart.maxRequestSize=4096MB
spring.jackson.default-property-inclusion=non_null
server.tomcat.connection-timeout=1800000
server.tomcat.basedir=/app/cache

tfs.copies=1
tfs.web-entrypoint=/
tfs.root-path=/app
tfs.path-prefix=/app/data/
tfs.config=/app/db.json
tfs.ffmpeg-url=/app/ffmpeg/bin/ffmpeg

etcd.endpoints=http://etcd:2379

meili-search.url=http://meilisearch:7700
meili-search.master-key=default_key
meili-search.web-ui=/

# SSO Configuration
sso.server-url=https://mail-api.nihilx.com
sso.info-url=http://mail.nihilx.com/sso/info
sso.cookie-name=sso_token
sso.enabled=true