server.port=8181
spring.config.activate.on-profile=win
spring.servlet.multipart.maxFileSize=4096MB
spring.servlet.multipart.maxRequestSize=4096MB
spring.jackson.default-property-inclusion=non_null

server.tomcat.basedir=d:\\res\\tfs\\cache
tfs.root-path=d:\\res\\tfs
tfs.web-entrypoint=http://127.0.0.1:8181
tfs.copies=1

etcd.endpoints=http://127.0.0.1:2379

meili-search.url=http://127.0.0.1:7700
meili-search.master-key=TheBindingOfIssac
meili-search.web-ui=http://127.0.0.1:7700